### PR TITLE
Fixed gitignore Problem

### PR DESCRIPTION
**Pull request by TonyZhang20**
Please everyone change your gitignore file, you can try to open your project after download from the github
all the source are missing!!!!!!!

### CODE REVIEW

**Comment by MasonJason23** [comment]
Hello @TonyZhang20 

I noticed there are two `.gitignore` files.
The `.gitignore` file that is in [this directory](https://github.com/danielreyes2873/CST-326-Final-Project/pull/5/files#diff-2144cc5e3faa34cfd298c16f958cbe1c537ef26dcefa9c64947a87980aed4165) is empty, so does that mean it would be okay to delete this file?

**Comment by MasonJason23** [comment]
Actually, never mind. That `.gitignore` file is not empty and is also needed. I deleted it on my end and a lot of changes that were supposed to be ignored were now recognized.

**Review by MasonJason23 — APPROVED** [review]
All good to go! Thanks for fixing the `.gitignore` problem.

**Comment by danielreyes2873** [comment]
lgtm

**Review by danielreyes2873 — COMMENTED** [review]
lgtm

**Pull request merged**
