### PR TITLE
Health bar and Ammo Count Feature

### PR DESCRIPTION
**Pull request by MasonJason23**
- Re-created [`MTrantham_HealthBar`](https://github.com/danielreyes2873/CST-326-Final-Project/tree/MTrantham_HealthBar) branch as [`MTrantham_HealthBar2`](https://github.com/danielreyes2873/CST-326-Final-Project/tree/MTrantham_HealthBar2)
- Merge main into `MTrantham_HealthBar2` branch and manually resolved any conflicts
- Replaced any missing assets as their original counter parts

### CODE REVIEW

**Comment by Markudi** [comment]
I took a look at the new branch. Seems good.

**Comment by MasonJason23** [comment]
Before merging this PR I just realized that there are 2 directories that should be ignored (`.idea/...`).

I assume this is due to the fact that our `.gitignore` file doesn't have the code to ignore files from the IntelliJ IDEA IDE. I will be working on this, so don't merge this PR just yet.

**Comment by MasonJason23** [comment]
Alright, this PR is good to go. @Markudi could you test this branch again to see if you are not getting anything weird on your end?

**Comment by Markudi** [comment]
Everything is working on myside. Sprites, text, etc are all in place.

**Pull request merged**
