### PR TITLE
Myk g level 1 design

### PR DESCRIPTION
**Pull request by Myk-G**
Another part of the level is created as a prefab.

### CODE REVIEW

**Comment by MasonJason23** [comment]
Hello @Myk-G 
Would you mind providing a link to the assets that you have imported? This will allow me to download those assets and see the geometry within the scene you've created because it is currently missing for me 👍

**Comment by MasonJason23** [comment]
@Myk-G There is a problem with your branch which is the reason why I am seeing missing assets when reviewing PR. Your branch is currently using an older version of the `.gitignore` files.

There are two `.gitignore` files on your branch you need to update. One right next to the "README.md" file and the other inside of "The_Slayer" directory. Once you have those updated, commit and push those changes for me to see.

**Comment by Myk-G** [comment]
oops my bad. That must have been when we update it in the main branch. Do I just copy the .gitignore file in the main branch and paste it in those two locations you mentioned?

**Comment by MasonJason23** [comment]
> oops my bad. That must have been when we update it in the main branch. Do I just copy the .gitignore file in the main branch and paste it in those two locations you mentioned?

Yup, that should do it.

**Comment by MasonJason23** [comment]
> oops my bad. That must have been when we update it in the main branch. Do I just copy the .gitignore file in the main branch and paste it in those two locations you mentioned?

Yup, that should do it.

**Comment by MasonJason23** [comment]
@Myk-G There are some conflicts between this branch and the main branch so I will manually resolve those conflicts in a cloned version of this branch just as a precaution. Then I will make a PR from that branch. 👍

**Pull request closed without merging**
